#pragma once

#define BOX_DISABLE_FASTPOOL		0
#define BOX_ENFORCE_GLOBAL_POOL		0

#define BOX_CONTAINER_POOLD_NODES	1

#define BOX_GLOBAL_POOL_ALIGNMENT	8192
#define BOX_ARRAY_POOL_ALIGNMENT	4096
#define BOX_NODE_POOL_ALIGNMENT		1024